# compose.local.yml (override local)
services:
  trxbewi_control:
    image: iobewi:trxbewi_control
    devices:
      - /dev/i2c-1:/dev/i2c-1 
    security_opt:
      - no-new-privileges:true   # pas --privileged
    init: true                 # démarre Tini -> forwarding propre des signaux
    stop_signal: SIGINT        # aligne Docker sur le signal attendu par ROS2